### ISSUE TITLE
Doliwoo makes checkout action eternal loading

### ISSUE THREAD

**Issue by sosoluis** [GPCsolutions/doliwoo#41]
When click on confirmation loading circle appears, doing nothing.

On Chrome, console shows:
POST https://www.sitename.com/wp-admin/admin-ajax.php?action=woocommerce_checkout 500 (Internal Server Error)jquery.js:4 m.ajaxTransport.sendjquery.js:4 m.extend.ajaxcheckout.min.js:1 (anonymous function)jquery.js:3 m.event.dispatchjquery.js:3 m.event.add.r.handle

**Comment by rdoursenaud** [comment]
Thirdparty and order creations are known to be broken right now.
I believe this is what triggers this behaviour since we don't touch any javascript.
We should push a fix next week.

**Comment by maxoumic** [comment]
Fixes

**Comment by sosoluis** [comment]
when i substitute with this new fix, wordpress is totally blank, whatever page!
