### ISSUE TITLE
Stock Synchronization

### ISSUE THREAD

**Issue by veeEn** [GPCsolutions/doliwoo#6]
Current Problem:
Shop A uses dolibarr for POS and WooCommerce for online sales. But it has a common physical inventory. The data has to be updated on WC everytime a customer buys at POS (through Dolibarr interface).

So, it requires synchronization of the stocks. Please allow the stocks to sync.

Thank you.

**Comment by rdoursenaud** [comment]
Thanks, added to our TODO list : 42593c29035c5b29fb39f1afa5755ad5304b5abf

**Comment by rdoursenaud** [comment]
Fixed by 0e1f43f3a06e8d838f1fdac2aabf8ec94898c0fa
