### ISSUE TITLE
Webservice error

### ISSUE THREAD

**Issue by Guitou46** [GPCsolutions/doliwoo#76]
Hi, 
I need some help to understand how can I fix this error : 
Webservice error:Function ("getVersions") is not a valid method for this service
- I try to use doliwoo to push my orders into dolibarr without SSL or OpenSSL certificate, in "sand box test mode" because OVH need some "euros" to put in place a certificate... 
- How I can edit "the code" to force the soap communication without HTTPS certificate to try this connector ? 
- Which webservices do i use to transmit the order to dolibarr, actually i use : 
  http://erp.mysite.fr/htdocs/webservices/server_other.php?wsdl
  Or 
  http://erp.mysite.fr/htdocs/webservices/server_user.php?wsdl

Nothing work...

Thank U

**Comment by rdoursenaud** [comment]
That getVersions error is suspiscous. What Dolibarr version are you using ?

Using without a valid SSL certificate is unsupported. Sorry, you're on your own for this one.

The webservice URL needed is the webservices root (http://erp.mysite.fr/htdocs/webservices). The module infers the various services URL itself. See instructions at https://gpcsolutions.github.io/doliwoo.

**Comment by Guitou46** [comment]
Thank U.
i try to use doliwoo, only order/client are create in Dolibarr : 
- There is no products in orders in dolibarr.
- No sync products into woocommerce, i have this errors : 
- getProductsForCategory request: Function ("getProductsForCategory") is not a valid method for this service
- getProductsForCategory response: NOT_FOUND: Object not found for id=1
- getProductsForCategory request: Internal Server Error

@rdoursenaud : I put some questions in dolibarr forum, I'm really interesting by your module....
If you want you can see here : 
http://www.dolibarr.fr/forum/12-howto--aide/51458-dolibarr-wordpress-woocommerce?start=15

And... sorry for my english, i'm french...

**Comment by rdoursenaud** [comment]
The module is designed to pull products from a product category in Dolibarr.
This is to avoid a full sync for users that are not pure ecommerce players and have fine grained control over which product are pulled by woocommerce directly from Dolibarr.
Have you created such a category? Have you declared it correctly in Doliwoo's configuration?
The error sounds like you have no category.

**Comment by rdoursenaud** [comment]
Oh, and by the way, if you want commercial support, we're available at https://gpcsolutions.fr to talk.
Yes, we're making free software, no we're not working for free ;)

**Comment by rdoursenaud** [comment]
#77 duplicate

**Comment by accett** [comment]
Hi Raphaël!

I want support but in Spanish or at least in English. To what mail can I
write you for make me  proposal?

Thanks.

**Comment by rdoursenaud** [comment]
Hi,

Sorry for the late reply. I've been on holidays and your message was buried
in my countless GitHub notifications.

Please use contact@gpcsolutions.fr.

We don't speak spanish very well despite school training but we can
certainly use english!

Looking forward to reading from you.

2015-08-13 3:45 GMT+02:00 AcceTT Soluciones Computacionales <
notifications@github.com>:

> Hi Raphaël!
> 
> I want support but in Spanish or at least in English. To what mail can I
> write you for make me proposal?
> 
> Thanks.
> El jul 23, 2015 2:57 a.m., "Raphaël Doursenaud" notifications@github.com
> escribió:
> 
> > #77 https://github.com/GPCsolutions/doliwoo/issues/77 duplicate
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/GPCsolutions/doliwoo/issues/76#issuecomment-124011063>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GPCsolutions/doliwoo/issues/76#issuecomment-130503215
> .

## 

_Raphaël Doursenaud_
Directeur technique (CTO)
Expert certifié en déploiement Google Apps
https://gpcsolutions.fr/raphael-doursenaud-google-apps-certified-deployment-specialist
+33 (0)5 35 53 97 13 - +33 (0)6 68 48 20 10

## 

 http://gpcsolutions.fr
http://gpcsolutions.fr
Technopole Hélioparc
2 avenue du Président Pierre Angot
64053 PAU CEDEX 9
SARL GPC.solutions au capital de 7 500 € - R.C.S. PAU 528 995 921
http://wiki.dolibarr.org/index.php/Dolibarr_suppliers_France#GPC.solutions
