### ISSUE TITLE
Dolibarr 3.7 compatibility

### ISSUE THREAD

**Issue by rdoursenaud** [GPCsolutions/doliwoo#77]
Looks like the module does not work anymore with Dolibarr 3.7.x

**Comment by BebZ** [comment]
Looks like someone found the solution by overwriting the webservices folder of 3.7.x with its older folder of 3.6.1.

**Comment by rdoursenaud** [comment]
@BebZ Yep, seen that but that's an ugly hack.
The changes made in 3.7 are important! Some SQL requests use different parameters.
In short, it seem to work but is bound to break with invalid data or the likes.
A proper fix is needed.

**Comment by rdoursenaud** [comment]
Upstream bug: https://github.com/Dolibarr/dolibarr/issues/3262
Fix cooked.
Waiting for upstream to pull it: https://github.com/Dolibarr/dolibarr/pull/3263
Apply manually if needed in the meantime.
