### ISSUE TITLE
Webservice error:Bad Request

### ISSUE THREAD

**Issue by ghost** [GPCsolutions/doliwoo#78]
Hello
I've setted up everything but when I save it give me this error "Webservice error:Bad Request"

I've looked all logs and I don't get any error.

Regards.

**Comment by rdoursenaud** [comment]
What version of Dolibarr are you using?

There's a known issue with the current stable (3.7.1). See #77.

**Comment by ghost** [comment]
Hello, yes I've the 3.7.1, so I just have to apply a patch ? 

Regards.

**Comment by rdoursenaud** [comment]
Yes, or wait for a 3.7.2 ;)
