### ISSUE TITLE
documentation improvements

### ISSUE THREAD

**Issue by altairis-tof** [GPCsolutions/doliwoo#85]
dont forget to give dolibarr user permissions needed by doliwoo (dolibarr webservice permission checks is not done everywhere - ie order creation or update does not check permissions, so you can easyly forget to set them but you will have a problem later when doliwoo try to do a fetch of the order, because the permissions are checked at this moment ! (reported on dolibarr dev mailing list)

**Comment by rdoursenaud** [comment]
This is already documented in the french user manual (Check the [wiki](https://github.com/GPCsolutions/doliwoo/wiki/User-manual)).
With #65 fixed, I guess this ground will be covered.

Feel free to comment so I can reopen the bug if you think this is not enough.

**Comment by altairis-tof** [comment]
great ! i haven't seen the wiki before; i will look at it tomorrow ! Thanks and good night
