### ISSUE TITLE
Dolliwoo localhost

### ISSUE THREAD

**Issue by webmasterrppd** [GPCsolutions/doliwoo#87]
Hi!
I try to activate dolliwoo in localhost.
But when I save show this message:
The webservice is not available. Please check the URL.

I don't know if the problem is the url our the localhost.
I hope you can help

thanks

**Comment by rdoursenaud** [comment]
Sorry this is not a support forum.
All I can say is that you must use a fully qualified domain name and have properly signed HTTPS connectivity to it, even on localhost.
