### ISSUE TITLE
Dolliwoo connection

### ISSUE THREAD

**Issue by webmasterrppd** [GPCsolutions/doliwoo#89]
Good Morning;
I installed the plugin on my online store woocommerce however it never synchronized ...
It gives an error as to the url webservice ..
Does anyone know how to solve this problem ?
( I would like to get some support plugin can be even paid support )

**Comment by rdoursenaud** [comment]
What's the error message?
In general, if it gives an error about the webservice URL, the webservice is not working properly on the Dolibarr side.
Also bear in mind that this project is not yet ready for prime time (See the README.md).
Don't use it on your production shop unless you absolutely know what you're doing.

**Comment by webmasterrppd** [comment]
Good morning;
 The erro is:
"The webservice is not available. Please check the URL."

We are trying to connect dollibarr in our test site, that have ssl, but it do not work..
The dolibarrr is not ours, is from a cliente..
Do you now how to correct this erro?

The client says that dolibarr web service is working fine..

**Comment by BebZ** [comment]
Is it on 2 different servers ? 
If no. see if you can separate them on 2 different. May be the problem. Really.

If yes. See if server 1 and 2 don't have a fail2ban or something like whitelist ip addresses... prevent ting them to communicate ;)

If nothing works re check user credentials on both sides.

**Comment by webmasterrppd** [comment]
Dona Silvia;
Este foi o mail que recebi do doliwoo;

**Comment by rdoursenaud** [comment]
Issue has not received a reply in a long time. Closing.
Feel free to reopen if you have valuable informations to share.
