### ISSUE TITLE
Still developed?

### ISSUE THREAD

**Issue by bf8392** [GPCsolutions/doliwoo#97]
Hi =) I'm looking for a solution to connect woocommerce to dolibarr, and this is the only one I found. I run Dolibarr 11.0.3 would this fit?

**Comment by dpriskorn** [comment]
Probably not, as it is dead as it seems. Try the Splash module instead: https://www.splashsync.com/en/modules/dolibarr

**Comment by bf8392** [comment]
Thanks :-) i already looked Info it, but it seems that I need their Server for that...I wanted something selfhosteable and free of monthly fees :-)

**Comment by dpriskorn** [comment]
Then try this: https://github.com/OPEN-DSI/ecommerceng_woosync
